export const FLOGO_LANGUAGE_FILE_EXTENSION = '.json'
export const FLOGO_LANGUAGE_FILE_NAME_NO_EXT = 'flogo'
export const FLOGO_LANGUAGE_FILE_NAME = FLOGO_LANGUAGE_FILE_NAME_NO_EXT + FLOGO_LANGUAGE_FILE_EXTENSION
export const FLOGO_LANGUAGE_SERVER_ID = 'flogo'
export const FLOGO_LANGUAGE_SERVER_NAME = 'Flogo'